- config:
    phases:
      - pre-run
      - edit
      - analysis
    files:
      - filter:
          tag: py
          regex: ".*\\.py$"
      - filter:
          tag: json
          regex: ".*\\.(json)$"
      - filter:
          tag: spell
          regex: ".*\\.(py|yml|json)$"
    options:
      - option:
          default: true
          name: black
          type: bool
          desc: allow/disallows py-black from running
      - option:
          alias: check
          default: false
          name: check_only
          type: bool
          desc: runs in check-mode, erroring if isort, black or any text-edits would occur
      - option:
          default: true
          desc: generates coverage reports for whatever can generate coverage info when added
          name: coverage
          type: bool
      - option:
          default: true
          desc: formats docs and comments in whatever job can do so
          name: docformatter
          type: bool
      - option:
          default: false
          name: generate call graphs
          type: bool
          desc: Generates call-graphs in jobs that can
      - option:
          default: false
          name: install deps
          type: bool
          desc: gets dep-installing job to run
      - option:
          default: true
          name: isort
          type: bool
          desc: allow/disallows isort from running on python files
      - option:
          default: true
          name: profile
          desc: generate profile information in jobs that can
          type: bool
      - option:
          alias: u
          default: true
          desc: update snapshots in jobs that can update data snapshots
          name: update snapshots
          type: bool
      - option:
          default: true
          desc: run unit tests
          name: unit test
          type: bool
      - option:
          default: false
          desc: run unit tests for the firebase function's data
          name: unit test firebase data
          type: bool
      - option:
          default: false
          desc: run unit tests for the python code
          name: unit test python
          type: bool
- job:
    addr:
      file: scripts/test-hooks/py.py
      function: _job_py_code_reformat
    label: reformat py
    when:
      phase: edit
      tags:
        - py
        - format
- job:
    addr:
      file: scripts/test-hooks/py.py
      function: _job_py_pylint
    label: pylint py
    when:
      phase: analysis
      tags:
        - py
        - lint
- job:
    addr:
      file: scripts/test-hooks/py.py
      function: _job_py_flake8
    label: flake8 py
    when:
      phase: analysis
      tags:
        - py
        - lint
- job:
    addr:
      file: scripts/test-hooks/py.py
      function: _job_py_mypy
    label: mypy py
    when:
      phase: analysis
      tags:
        - py
        - type
- job:
    addr:
      file: scripts/test-hooks/py.py
      function: _install_python_requirements
    label: install python requirements
    when:
      phase: pre-run
      tags:
        - py
- job:
    addr:
      file: scripts/test-hooks/json_validators.py
      function: _json_validate
    label: json validate
    when:
      phase: analysis
      tags:
        - json
- job:
    addr:
      file: scripts/test-hooks/yarn.py
      function: _job_spellcheck
    label: spell check
    when:
      phase: analysis
      tags:
        - spell
- job:
    addr:
      file: scripts/test-hooks/yarn.py
      function: _job_prettier
    label: prettier
    when:
      phase: analysis
      tags:
        - json
        - format
